version: "3.9"

services:

  elastic_search:
    build:
      context: ../..
      dockerfile: ./docker/elastic/Dockerfile
    container_name: elastic_search
    volumes:
      - local_elastic_search_data:/usr/share/elasticsearch/data
    networks:
      - local_network_search
      - shared_network
    healthcheck:
      test: [ "CMD", "curl", "--write-out", "'HTTP %{http_code}'",
              "--fail", "--silent", "--output", "/dev/null", "http://elastic_search:9200/" ]
      interval: 1s
      retries: 30
    env_file:
      - ../../.envs/.docker-compose-local/.elastic
    ports:
      - "9204:9200"
    expose:
      - "9200"

networks:
  shared_network:
    external: true
  local_network_search:
    driver: bridge

volumes:
  local_elastic_search_data: { }





