version: "3.9"

services:

  postgres_search:
    restart: always
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres_search
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/staticfiles/backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - local_network_search
      - shared_network
    env_file:
      - .envs/.prod/.postgres

  redis_search:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: redis_search
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 3s
      retries: 3
    networks:
      - local_network_search
    env_file:
      - .envs/.prod/.redis

  elastic_search:
    build:
      context: .
      dockerfile: ./docker/elastic/Dockerfile
    container_name: elastic_search
    volumes:
      - local_elastic_search_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "--write-out", "'HTTP %{http_code}'",
              "--fail", "--silent", "--output", "/dev/null", "http://elastic_search:9200/" ]
      interval: 1s
      retries: 30
    networks:
      - local_network_search
    env_file:
      - .envs/.prod/.elastic

  api_search:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      args:
        - BUILD_ENV=prod
    command: /start_prod
    container_name: api_search
    volumes:
      - local_postgres_data_backups:/app/staticfiles/backups
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - .:/app
    depends_on:
      elastic_search:
        condition: service_healthy
      postgres_search:
        condition: service_healthy
      redis_search:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail -f http://$$API_SEARCH_HOST:$$API_SEARCH_PORT/docs" ]
      interval: 3s
      retries: 3
    networks:
      - local_network_search
      - shared_network
    env_file:
      - .envs/.prod/.postgres
      - .envs/.prod/.api
      - .envs/.prod/.redis
    expose:
      - "8081"

  nginx_search:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_search
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - api_search
    networks:
      - local_network_search
    env_file:
      - .envs/.prod/.api
    ports:
      - "84:84"

networks:
  local_network_search:
    driver: bridge
  shared_network:
    external: true

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  local_elastic_search_data: { }
  static_volume:
  media_volume:
