#!/bin/bash

set -o errexit # if any command fails any reason, script fails
set -o pipefail # if none of of you pipecommand fails, exit fails
set -o nounset # if none of variables set, exit


elastic_ready(){
   curl -IGET http://${ELASTIC_HOST}:${ELASTIC_PORT}
}

redis_ready(){
   nc -z ${REDIS_HOST} ${REDIS_PORT}
}

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

#until postgres_ready; do
#>&2 echo "Waiting for PostgreSQL to become available... 8-(("
#sleep 1
#done
#>&2 echo "PostgreSQL is ready!!! 8-))"
#
#until elastic_ready; do
#   >&2 echo "Waiting for ElasticSearch to become available... 8-(("
#   sleep 1
#done
#>&2 echo "ElasticSearch is ready!!! 8-))"
#
#until redis_ready; do
#   >&2 echo "Waiting for Redis to become available... 8-(("
#   sleep 1
#done
#>&2 echo "Redis is ready!!! 8-))"

exec "$@"
